### ISSUE TITLE
Create index and a way to turn it into an ePub

### ISSUE THREAD

**Issue by nick-s-b** [amirrajan/survivingtheappstore#7]
While there's a chapter on how to read a book, an index would go a long way in making this book more coherent. Also, I wish there was a way to put in on my ebook reader.

Thanks for the book and for sharing the knowledge!

**Comment by amirrajan** [comment]
Added a table of contents/order to read the markdown files in: https://github.com/amirrajan/survivingtheappstore/blob/master/README.md#table-of-contents

You can probably use Pandoc to generate a pdf.
